name       : ki18n
version    : 5.44.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/ki18n-5.44.0.tar.xz : 8cdd6337798a6382b25933f9ad89f4bf9082c18bed03acb5cfbd163d5124e2e5
license    :
    - BSD-3-Clause
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : KDE Gettext-based UI text internationalization.
description: |
    KDE Gettext-based UI text internationalization.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
