name       : ki18n
version    : 5.38.0
release    : 7
source     :
    - https://download.kde.org/stable/frameworks/5.38/ki18n-5.38.0.tar.xz : 240ccf22a65cf85da900c88afceac8bedc40b71a4d19bad526c03aa285cc2a7d
license    :
    - BSD-3-Clause
    - LGPL-2.1
component  : programming
summary    : KDE Gettext-based UI text internationalization.
description: |
    KDE Gettext-based UI text internationalization.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
