name       : ki18n
version    : 5.43.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/ki18n-5.43.0.tar.xz : 8a802507ba6a5a91470d09c649e842843d70f37968d86473567928f2cdee57ff
license    :
    - BSD-3-Clause
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : KDE Gettext-based UI text internationalization.
description: |
    KDE Gettext-based UI text internationalization.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
