name       : ki18n
version    : 5.32.0
release    : 4
source     :
    - http://download.kde.org/stable/frameworks/5.32/ki18n-5.32.0.tar.xz : 4ee7c032f2ff6f86af6d6171d4eef3ee0c66816c523e5e90bc14120f05df1d19
license    :
    - BSD-3-Clause
    - LGPL-2.1
component  : programming
summary    : KDE Gettext-based UI text internationalization.
description: |
    KDE Gettext-based UI text internationalization.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
