name       : ki18n
version    : 5.78.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.78/ki18n-5.78.0.tar.xz : 13352d2ce158c09edde129712adc12ca50c81bbcafe2df924192b5faf2dc4e55
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.tools
optimize   : lto
summary    : KDE Gettext-based UI text internationalization.
description: |
    KDE Gettext-based UI text internationalization.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
