name       : ki18n
version    : 5.64.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/ki18n-5.64.0.tar.xz : ccd2c2f8b14251701f902c9e7d046da1582e544d31edae743911f3554022d024
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : KDE Gettext-based UI text internationalization.
description: |
    KDE Gettext-based UI text internationalization.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
