name       : ki18n
version    : 5.66.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.66/ki18n-5.66.0.tar.xz : 9622337a513fcb8f0b5100c218b9fa85617f92024e5d7feada6d071f58a329e3
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : KDE Gettext-based UI text internationalization.
description: |
    KDE Gettext-based UI text internationalization.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
