name       : ki18n
version    : 5.36.0
release    : 6
source     :
    - https://download.kde.org/stable/frameworks/5.36/ki18n-5.36.0.tar.xz : c0c9877a7c4f4d0630e934a903cc27fd127d0be63531c50ea77d63e10119558b
license    :
    - BSD-3-Clause
    - LGPL-2.1
component  : programming
summary    : KDE Gettext-based UI text internationalization.
description: |
    KDE Gettext-based UI text internationalization.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
