name       : ki18n
version    : 5.39.0
release    : 8
source     :
    - https://download.kde.org/stable/frameworks/5.39/ki18n-5.39.0.tar.xz : 5e31cac2735db66de620d28a5d561f15aaafd6181c1ff7ca3a03b20ce3c305a5
license    :
    - BSD-3-Clause
    - LGPL-2.1
component  : programming
summary    : KDE Gettext-based UI text internationalization.
description: |
    KDE Gettext-based UI text internationalization.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
