name       : ki18n
version    : 5.51.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/ki18n-5.51.0.tar.xz : 7219dcdf8b295122b45e3990cd46c0c21531704cbc0b0d918776a99fb228d393
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : KDE Gettext-based UI text internationalization.
description: |
    KDE Gettext-based UI text internationalization.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
