name       : ki18n
version    : 5.42.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.42/ki18n-5.42.0.tar.xz : a9cb8ced1284b7b983b609f93da9a596e09f0d1d06befe49928828b1a88bf9e6
license    :
    - BSD-3-Clause
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : KDE Gettext-based UI text internationalization.
description: |
    KDE Gettext-based UI text internationalization.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
