name       : ki18n
version    : 5.25.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.25/ki18n-5.25.0.tar.xz : 5d9ae669b2c6a7637489ffb04d603762512fe8c78501ea5318acc387741e7167
license    :
    - BSD-3-Clause
    - LGPL-2.1
component  : desktop.library
summary    : KDE Gettext-based UI text internationalization.
description: |
    KDE Gettext-based UI text internationalization.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
