name       : ki18n
version    : 5.35.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.35/ki18n-5.35.0.tar.xz : 8e7d88d8a27fc466257caa0f0871fbd4fb56c674c9fbb6567e87da933b221ea5
license    :
    - BSD-3-Clause
    - LGPL-2.1
component  : programming
summary    : KDE Gettext-based UI text internationalization.
description: |
    KDE Gettext-based UI text internationalization.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
