name       : ki18n
version    : 5.47.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/ki18n-5.47.0.tar.xz : 2627faa0186e9b463d978e842bf6df1e7d27e7e9d487793f6709e82a1c0729a8
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : KDE Gettext-based UI text internationalization.
description: |
    KDE Gettext-based UI text internationalization.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
