name       : ki18n
version    : 5.50.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/ki18n-5.50.0.tar.xz : 29fc301cb0b465c88fc58be5a11094434065056c232dc19c5ef05aaf7e54cbf8
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : KDE Gettext-based UI text internationalization.
description: |
    KDE Gettext-based UI text internationalization.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/Fix-tests.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
